@startuml
|User|
start


|User|
:Navigate to main calendar (home page);

|Calendar|
:Load Tasks;
:Display home page;

|User|
:Select "Preferences";

|Calendar|
:Hide Homepage;

|Preferences|
:Load Preferences from file;
:Display Preferences page;

|User|
:Select "Categories";

|Preferences|
:Display categories list;

|User|
:Select color;

|Calendar|
:Display color dropdown including:
-RED:
-GREEN:
-BLUE:
-PURPLE:
-ORANGE;

|User|
:Select "RED" from dropdown;

|Preferences|
:Update category color to red;
:Write new category color to preferences file;

|User|
:Select "Done";

|Preferences|
:Hide preferences page;

|Calendar|
:Show HomePage;

|User|
:Verify that "test task" appears as red in the task list;
:verify that "test event" appears as red in the event list;
stop

@enduml
