@startuml
|User|
start

|System|
:Ensure program is installed;

|User|
:Open the program;

|Settings|
:Sign up for the app;

note right
Sign up Fields:
- Name
- Email
- Date of birth
- <color:red> Phone number </color>
- Passowrd
end note

|System|
:Validate sign up info;

|User|
:Navigate to main calendar (home page);

|User|
:Add the task with desired due date;
:Select "CONFIRM";

|System|
:Validate task data;

note right
- Name: test task:
- Priority
- Date
- Category
- Description
end note

|System|
if (data valid?) then (yes)
  :An SMS will be received 10 minutes before the due date;
else (no)
  :Show error message;
  :Return to main calendar;
stop
endif
 
stop

@enduml