@startuml
|User|
start
:Open the app; 

|System|
:Ensure the program is installed;
:Load user data and settings; 

|User|
:Hide Welcome Screen;

|System|
:Display homepage;

|Task|
:Check for missed or incomplete tasks; 

|User|
:Click on the task on the calendar to reschedule;
:Click "Reschedule" button; 

|Task|
:Generate rescheduling suggestions; 

|System|
:Display suggestions to user; 

|User|
if (Select reschedule option) then (Suggested date)

else (Manual entry)


  :Manually enter date;

|System|
:Validate date;
if (Is date entered valid?) then (Yes)

else (No)
:Display error message; 
:Return to homepage; 
  stop
 endif
 endif

|Task|
:Update task due date; 

|System|
:Display task on main calendar;

|User|
: Verify that task appears in the rescheduled date in the calendar;
stop


@enduml
