@startuml
|User|
start
:Navigate to main calendar (home page);

|Calendar|
:Load tasks;
:Display calendar;

|User|
:Select "GET TASKS";
:Select "DATE" option;
:Select current date on calendar;
:Select "GET DATE";

|Calendar|
if (Search type) then (Date)
  :Get all tasks with matching Date;
else (!Date)
  if (Search type) then (Category)
    :Get all tasks with matching Category;
  else (!Category)
    :Get all tasks with matching Name;
  endif
endif
:Display tasks in the list;

note right
If nothing was found
a blank list is displayed
end note

|User|
:Verify that the valid tasks exist in the results;
:Select "GET TASKS";
:Select "CATEGORY" option;
:Select the "ACADEMIC" tag;
:Select "GET CATEGORY";

|Calendar|
if (Search type) then (Date)
  :Get all tasks with matching Date;
else (!Date)
  if (Search type) then (Category)
    :Get all tasks with matching Category;
  else (!Category)
    :Get all tasks with matching Name;
  endif
endif
:Display tasks in the list;

note right
If nothing was found
a blank list is displayed
end note

|User|
:Verify that the valid tasks exist in the results;

stop

@enduml
