@startuml
|User|
start

|User|
:Navigate to main calendar (home page);

|Calendar|
:Load Tasks;
:Display Calendar;
:Display TaskList;

|User|
:Select the "TestTask" from task list;

|Calendar|
:Display option to edit task;

|User|
:Select "edit task";

|Calendar|
:Display "Edit Task" form;

|User|
:Select the field;
- Priority: medium;

|Calendar|
:Display dropdown including:
- Low Priority:
- Medium Priority:
- High Priority;

|User|
:Select High Priority;
:Select "Done";

|Calendar|
:Hide "Edit Task" form;

|Task|
:Update "TestTask" priority to "High Priority;

|User|
:Verify that the tasks priority has changed in the task list;
:Verify that the tasks sorting in task list has updated so it appears first;
stop

@enduml
