@startuml

class Calendar {
  +uniqueID: int  
  +taskAmount: int
  +eventAmount: int
  +addTask(): createTask()
  +removeTask(param: taskID): void
  +editTask(param: eventID): void
  +addEvent(): create_event()
  +removeEvent(param: eventID): void
  +editEvent(param: eventID): void
  +getTasksByDate(date: Date): List <Tasks>
  +getTasksByName(string: Name): List <Tasks>
  +getEventsByDate(): get_events_by_date()
  +getEventsByName(): get_events_by_name()
  +getEventsByLocation(): get_events_by_location()
}

class Task {
}

class Event {
}

Calendar "1" *-- "0 *" Task
Calendar "1" *-- "0 *" Event

@enduml
