@startuml

class DailyOverview {
    +uniqueID: int
    +date: Date
    +tasksForToday: List<Task>
    +overviewPrompt: String

    +displayOverviewPrompt(): void
    +getTasksForToday(calendar: Calendar): List<Task>
    +sortTasksByPriority(): void
    +sortTasksByDueTime(): void
    +addRelevantInfo(param: String): void
}

Calendar "1" -- "1" DailyOverview

@enduml
