@startuml

class Daily_Overview {
    -unique_id: int
    -date: Date
    -tasks_for_today: list<tasks>
    -overview_prompt: String

    +display_overview_prompt(): void
    +get_tasks_for_today(calendar: get_tasks_by_date()): List<Task>
    +sort_tasks_by_priority(): void
    +sort_tasks_by_due_time(): void
    +add_relevant_info(param: String): void
}

Calendar "1" o-- "1" Daily_Overview : "generates"

@enduml
