@startuml

class User {
  +Name: String
  +University: String
  +Age: int
  +Major: String
  +Dark_mode: Boolean
  +Font_size: int
  +setName(params:String): void
  +setUni(param: String): void
  +setAge(param: int): void
  +setMajor(param: String): void
  +setFsize(param: int): void
  +setMode(param: boolean): void
  +getName(): String
  +getUni(): String
  +getAge(): int
  +getMajor(): String
  +getFsize(): int
  +getMode(): Boolean
 
}

class Calendar {
  +uniqueID: int  
  +taskAmount: int
  +eventAmount: int
  +addTask(): createTask()
  +removeTask(param: taskID): void
  +editTask(param: eventID): void
  +addEvent(): create_event()
  +removeEvent(param: eventID): void
  +editEvent(param: eventID): void
  +getTasksByDate(date: Date): List <Tasks>
  +getTasksByName(string: Name): List <Tasks>
  +getEventsByDate(): get_events_by_date()
  +getEventsByName(): get_events_by_name()
  +getEventsByLocation(): get_events_by_location()
}

class Task {
  +uniqueID: int
  +title: string
  +description: string
  +dueDate: Date
  +priority: int
  +status: int
  +createTask(params: int, string, string, Date): int
  +setTitle(param: String): void
  +setDate(param: Date): void
  +setDescription(param: String): void
  +setPriority(param: int): void
  +complete(): void
  +getStatus(): int
  +getDueDate(): Date
}

class Category {
  +title: String
  +color: String
}

class Notification {
  +uniqueID: int  
  +date: Date
  +alert: string
  
  +set_reminder_time(param: Date): void
  +set_alert(param: string): void
  +get_tasks_by_date(): List<Task>
  +get_task_name(param: Task): void
  +get_task_status(param: Task): void
  +get_events_by_date(): List<Task>
  +get_event_name(param: Task): void
  +get_event_status(param: Task): void
  +create_feedback(param: Task): void
  +display_notification(): void
}

class Event {
  +unique_id: int  
  +name: string
  +description: string
  +start_time: Date
  +end_time: Date
  +location: string
  +create_event(string, string, string, string, Date, Date): int
  +set_name(param: string): void
  +set_description(param: string): void
  +set_location(param: string): void
  +set_start_time(param: Date): void
  +set_end_time(param: Date): void
  +get_events_by_name(): List<Event>
  +get_events_by_date(): List<Event>
  +get_events_by_location(): List<Event>
}

class DailyOverview {
    +uniqueID: int
    +date: Date
    +tasksForToday: List<Task>
    +overviewPrompt: String

    +displayOverviewPrompt(): void
    +getTasksForToday(calendar: Calendar): List<Task>
    +sortTasksByPriority(): void
    +sortTasksByDueTime(): void
    +addRelevantInfo(param: String): void
}

class Management {
  +manageUser(): void
  +manageCalendar(): void
  +CreateTasks(param: Task): void
  +CreateEvents(param: Event): void
  +sendNotifications(): void
}

Management -- User
Management -- Calendar
Management -- Task
Management -- Events
Management -- Notification

Calendar "1" -- "1" User
Calendar "1" *-- "0 *" Task
Calendar "1" *-- "0 *" Events
Task ..> Notification: uses
Event ..> Notification: uses
Calendar "1" -- "1" DailyOverview


@enduml
