@startuml

class Task {
  -unique_id: int
  -title: string
  -description: string
  -due_date: Date
  -priority: int
  -status: int
  +create_task(params: int, string, string, Date): int
  +set_title(param: String): void
  +set_date(param: Date): void
  +set_description(param: String): void
  +set_priority(param: int): void
  +complete(): void
  +get_status(): int
  +get_due_date(): Date
}

enum Category {
  WORK
  SCHOOL
  HOME
  PERSONAL
  OTHER
}

Task --> Category : "has single select"

@enduml