@startuml

class Task {
  +uniqueID: int
  +title: string
  +description: string
  +dueDate: Date
  +priority: int
  +status: int
  +createTask(params: int, string, string, Date): int
  +setTitle(param: String): void
  +setDate(param: Date): void
  +setDescription(param: String): void
  +setPriority(param: int): void
  +complete(): void
  +getStatus(): int
  +getDueDate(): Date
}

class Category {
  +title: String
  +color: String
}

Task "0" *-- "1*" Category

@enduml
