@startuml

class User {
  +Name: String
  +University: String
  +Age: int
  +Major: String
  +Dark_mode: Boolean
  +Font_size: int
  +setName(params:String): void
  +setUni(param: String): void
  +setAge(param: int): void
  +setMajor(param: String): void
  +setFsize(param: int): void
  +setMode(param: boolean): void
  +getName(): String
  +getUni(): String
  +getAge(): int
  +getMajor(): String
  +getFsize(): int
  +getMode(): Boolean
 
}

class Calendar{
  
}

Calendar "1" -- "1" User



@enduml
