@startuml

class User {
  -Name: String
  -University: String
  -Age: int
  -Major: String
  -Dark_mode: Boolean
  -Font_size: int
  +set_name(params:String): void
  +set_uni(param: String): void
  +set_age(param: int): void
  +set_major(param: String): void
  +set_fsize(param: int): void
  +set_mode(param: boolean): void
  +get_name(): String
  +get_uni(): String
  +get_age(): int
  +get_major(): String
  +get_fsize(): int
  +get_mode(): Boolean
 
}

class Calendar{
  
}

Calendar "1" -- "1" User



@enduml
